### ISSUE TITLE
Interface method beginning with get appear in generated schema

### ISSUE THREAD

**Issue by jmoney8080** [FasterXML/jackson-dataformat-avro#30]
private interface Bomb {
        String getBomb();
    }

    private static class MyBomb implements Bomb {

        private String bomby;

        public String getBomby() {
            return bomby;
        }

        public void setBomby(String bomby) {
            this.bomby = bomby;
        }

        @Override
        public String getBomb() {
            return bomby;
        }
    }

So I have the above.  There is no field for "bomb" in MyBomb but it will still show up in the schema.  getBomb is an interface method so I'm unsure why it shows up in the schema.  https://github.com/jmoney8080/jackson-dataformat-avro/commit/2c37508253fdb0e65281454189bcbecbd2dcbcbf

The above commit adds a test showing the issue.

**Comment by cowtowncoder** [comment]
This is because there is logical property `bomb`, induced by getter `getBomb()`; and as such property will be included. Jackson does not base schema definitions on existence of particular fields, but only on logical properties.

One way to achieve what you want would to enable `MapperFeature. REQUIRE_SETTERS_FOR_GETTERS`: this will prevent addition of any properties that can not be set.

**Comment by jmoney8080** [comment]
Thanks! That works great!

**Comment by jmoney8080** [comment]
Actually, is there a feature already in jackson that looks at the fields instead of logical fields?  I ask because i just noticed my use case has a getFoo and setFoo method, so that feature doesn't solve my use case completely

**Comment by cowtowncoder** [comment]
@jmoney8080 General rules are such that schema you get would describe behavior you would get for basic serialization -- so what you can do is to produce kind of JSON (etc) output that would confirm with  your schema. If that helps to think of how to solve this.

Now, as to discovery, yes; you can change "visibility rules" so that -- for example -- only fields of certain visibility are found; and that none of methods (setter, getter) are auto-discovered. There are annotations (`@JsonAutoDetect`) to do this for specific types; but also `ObjectMapper` has methods; `setVisibility` either for specific accessors, or defining your own `VisibilityChecker`.

For follow-up questions it would be great if we could continue on `jackson-users` google group, partly since other developers may be able to help you too, and partly so that other users can learn of solutions.
