### ISSUE TITLE
UnsupportedOperationException: Can not create generator for character-based (not byte-based) target

### ISSUE THREAD

**Issue by asmaier** [FasterXML/jackson-dataformat-avro#37]
The API to output the Avro schema as a string seems to be inconsistent compared with the API for https://github.com/FasterXML/jackson-module-jsonSchema. 

This works for JsonSchema:
   ```
 ObjectMapper mapper = new ObjectMapper();
 mapper.registerModule(new JavaTimeModule());
 mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);

 SchemaFactoryWrapper visitor = new SchemaFactoryWrapper();
 mapper.acceptJsonFormatVisitor(File.class, visitor);
 JsonSchema schema = visitor.finalSchema();

 System.out.println("Jackson Json Schema:");
 System.out.println(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(schema));
```
But for AvroSchema this will throw an UnsupportedOperationException in the last line:
```
ObjectMapper mapper = new ObjectMapper(new AvroFactory());
mapper.registerModule(new JavaTimeModule());
mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);

AvroSchemaGenerator visitor = new AvroSchemaGenerator();
mapper.acceptJsonFormatVisitor(File.class, visitor);
AvroSchema schema = visitor.getGeneratedSchema();

System.out.println("Jackson Avro Schema:");
System.out.println(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(schema));
```

I just thought it would be nice, if both APIs would work in the same way.

P.S.: I used version 2.6.3 for Avro Schema and for Json Schema.

**Comment by cowtowncoder** [comment]
The problem here is that you are trying to output Avro schema _as Avro_, and Avro format is binary; it can not be serialized as text.
If you want to output it as String you most likely want to write it as JSON instead, so you should be using JSON-backed `ObjectMapper`.

But it is probably valid point that it would be nice to have a convenient way to output Avro Schema as a JSON string -- so I'll keep this issue open to think about best way to do that.
